package ui;


import Domain.AddSkill;
import Model.ShareCode;
import java.awt.Color;
import java.awt.Component;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.event.MouseListener;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.*;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hassan Usman
 */
public class DashDesign extends javax.swing.JFrame {

    /**
     * Creates new form DashDesign
     */
    public DashDesign() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblAppName = new javax.swing.JLabel();
        lblOverview = new javax.swing.JLabel();
        lblDocuments = new javax.swing.JLabel();
        lblSkills = new javax.swing.JLabel();
        lblVideos = new javax.swing.JLabel();
        CodeBtn = new javax.swing.JLabel();
        CodeDisp = new javax.swing.JTextField();
        lblskills = new javax.swing.JLabel();
        copybtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblVideo = new javax.swing.JLabel();
        lblNoVideos = new javax.swing.JLabel();
        lblV1 = new javax.swing.JLabel();
        lblDashboardTit = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblPeopleV = new javax.swing.JLabel();
        lblNoPeople = new javax.swing.JLabel();
        lblP1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblDocument = new javax.swing.JLabel();
        lblNoDocuments = new javax.swing.JLabel();
        lblD1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblEmployerInt = new javax.swing.JLabel();
        lblInt1 = new javax.swing.JLabel();
        lblInt2 = new javax.swing.JLabel();
        lblInt3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        PanelMenu.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        lblAppName.setBackground(new java.awt.Color(51, 153, 255));
        lblAppName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblAppName.setForeground(new java.awt.Color(255, 255, 255));
        lblAppName.setText("ADV Job Portal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAppName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAppName, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblOverview.setBackground(new java.awt.Color(0, 153, 153));
        lblOverview.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblOverview.setForeground(new java.awt.Color(255, 255, 255));
        lblOverview.setText("Overview");
        lblOverview.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOverview.setOpaque(true);
        lblOverview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOverviewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOverviewMouseExited(evt);
            }
        });

        lblDocuments.setBackground(new java.awt.Color(0, 153, 153));
        lblDocuments.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblDocuments.setForeground(new java.awt.Color(255, 255, 255));
        lblDocuments.setText("Documents");
        lblDocuments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDocuments.setOpaque(true);
        lblDocuments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDocumentsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDocumentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDocumentsMouseExited(evt);
            }
        });

        lblSkills.setBackground(new java.awt.Color(0, 153, 153));
        lblSkills.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblSkills.setForeground(new java.awt.Color(255, 255, 255));
        lblSkills.setText("Menu");
        lblSkills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSkills.setOpaque(true);
        lblSkills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSkillsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSkillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSkillsMouseExited(evt);
            }
        });

        lblVideos.setBackground(new java.awt.Color(0, 153, 153));
        lblVideos.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblVideos.setForeground(new java.awt.Color(255, 255, 255));
        lblVideos.setText("Videos");
        lblVideos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVideos.setOpaque(true);
        lblVideos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVideosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVideosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVideosMouseExited(evt);
            }
        });

        CodeBtn.setBackground(new java.awt.Color(0, 153, 153));
        CodeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CodeBtn.setForeground(new java.awt.Color(255, 255, 255));
        CodeBtn.setText("Generate Code to Share Profile");
        CodeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CodeBtn.setOpaque(true);
        CodeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CodeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CodeBtnMouseExited(evt);
            }
        });

        CodeDisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodeDispActionPerformed(evt);
            }
        });

        lblskills.setBackground(new java.awt.Color(0, 153, 153));
        lblskills.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblskills.setForeground(new java.awt.Color(255, 255, 255));
        lblskills.setText("Add Skills");
        lblskills.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblskills.setOpaque(true);
        lblskills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblskillsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblskillsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblskillsMouseExited(evt);
            }
        });

        copybtn.setText("Copy");
        copybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copybtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(CodeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CodeBtn)
                            .addComponent(lblVideos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDocuments, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOverview, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSkills, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblskills, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(copybtn)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblOverview)
                .addGap(30, 30, 30)
                .addComponent(lblDocuments)
                .addGap(29, 29, 29)
                .addComponent(lblVideos)
                .addGap(28, 28, 28)
                .addComponent(lblSkills)
                .addGap(26, 26, 26)
                .addComponent(lblskills)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CodeDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CodeBtn)
                .addGap(10, 10, 10)
                .addComponent(copybtn))
        );

        jPanel4.setBackground(new java.awt.Color(204, 0, 51));

        jPanel5.setBackground(new java.awt.Color(255, 102, 102));

        lblVideo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblVideo.setForeground(new java.awt.Color(255, 255, 255));
        lblVideo.setText("Videos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVideo, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNoVideos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNoVideos.setForeground(new java.awt.Color(255, 255, 255));
        lblNoVideos.setText("7");

        lblV1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblV1.setForeground(new java.awt.Color(255, 255, 255));
        lblV1.setText("Videos Uploaded");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(lblNoVideos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblV1)
                .addGap(74, 74, 74))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblNoVideos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblV1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblDashboardTit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDashboardTit.setText("Dashboard");

        jPanel6.setBackground(new java.awt.Color(204, 102, 0));

        jPanel7.setBackground(new java.awt.Color(255, 153, 102));

        lblPeopleV.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblPeopleV.setForeground(new java.awt.Color(255, 255, 255));
        lblPeopleV.setText("People Views");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPeopleV, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPeopleV, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNoPeople.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNoPeople.setForeground(new java.awt.Color(255, 255, 255));
        lblNoPeople.setText("1000");

        lblP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblP1.setForeground(new java.awt.Color(255, 255, 255));
        lblP1.setText("Viewers in Last 30 days");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblP1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblNoPeople)))
                .addGap(58, 58, 58))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lblNoPeople)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblP1)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(51, 204, 255));
        jPanel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel9.setBackground(new java.awt.Color(0, 153, 153));

        lblDocument.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblDocument.setForeground(new java.awt.Color(255, 255, 255));
        lblDocument.setText("Documents");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDocument, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblNoDocuments.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblNoDocuments.setForeground(new java.awt.Color(255, 255, 255));
        lblNoDocuments.setText("12");

        lblD1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblD1.setForeground(new java.awt.Color(255, 255, 255));
        lblD1.setText("Documents Uploaded");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lblD1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(lblNoDocuments)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblNoDocuments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblD1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));
        jPanel10.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(0, 153, 204));

        jPanel11.setBackground(new java.awt.Color(51, 204, 255));

        lblEmployerInt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblEmployerInt.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployerInt.setText("Employers Interactions");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEmployerInt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmployerInt)
                .addContainerGap())
        );

        lblInt1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblInt1.setForeground(new java.awt.Color(255, 255, 255));
        lblInt1.setText("~ Kashif viewed your Profile and gave Feedback");

        lblInt2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblInt2.setForeground(new java.awt.Color(255, 255, 255));
        lblInt2.setText("~ Kashif viewed your Profile and gave Feedback");

        lblInt3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblInt3.setForeground(new java.awt.Color(255, 255, 255));
        lblInt3.setText("~ Kashif viewed your Profile and gave Feedback");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInt1)
                    .addComponent(lblInt2)
                    .addComponent(lblInt3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblInt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInt3)
                .addGap(0, 74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDashboardTit)
                        .addGap(25, 667, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDashboardTit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOverviewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOverviewMouseEntered
        lblOverview.setBackground(new Color(51,110,123));// TODO add your handling code here:
    }//GEN-LAST:event_lblOverviewMouseEntered

    private void lblOverviewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOverviewMouseExited
       lblOverview.setBackground(new Color(0,153,153)); // TODO add your handling code here:
    }//GEN-LAST:event_lblOverviewMouseExited

    private void lblDocumentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocumentsMouseEntered
       lblDocuments.setBackground(new Color(51,110,123)); // TODO add your handling code here:
    }//GEN-LAST:event_lblDocumentsMouseEntered

    private void lblDocumentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocumentsMouseExited
       lblDocuments.setBackground(new Color(0,153,153)); // TODO add your handling code here:
    }//GEN-LAST:event_lblDocumentsMouseExited

    private void lblVideosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideosMouseEntered
lblVideos.setBackground(new Color(51,110,123));        // TODO add your handling code here:
    }//GEN-LAST:event_lblVideosMouseEntered

    private void lblVideosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideosMouseExited
      lblVideos.setBackground(new Color(0,153,153));  // TODO add your handling code here:
    }//GEN-LAST:event_lblVideosMouseExited

    private void lblSkillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSkillsMouseEntered
        lblSkills.setBackground(new Color(51,110,123));// TODO add your handling code here:
    }//GEN-LAST:event_lblSkillsMouseEntered

    private void lblSkillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSkillsMouseExited
       lblSkills.setBackground(new Color(0,153,153)); // TODO add your handling code here:
    }//GEN-LAST:event_lblSkillsMouseExited

    private void lblDocumentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDocumentsMouseClicked
     Documents a = new Documents();
     a.setVisible(true);
     this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_lblDocumentsMouseClicked

    private void lblVideosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideosMouseClicked
    Videos l= new Videos();
    l.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_lblVideosMouseClicked

    private void CodeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeBtnMouseEntered
      CodeBtn.setBackground(new Color(51,110,123));  // TODO add your handling code here:
    }//GEN-LAST:event_CodeBtnMouseEntered

    private void CodeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeBtnMouseExited
      CodeBtn.setBackground(new Color(0,153,153));  // TODO add your handling code here:
    }//GEN-LAST:event_CodeBtnMouseExited

    private void lblSkillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSkillsMouseClicked
     Menu m = new Menu();
     m.setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_lblSkillsMouseClicked

    private void CodeDispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodeDispActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodeDispActionPerformed

    private void CodeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CodeBtnMouseClicked
        ShareCode code= new ShareCode();
        CodeDisp.setText(code.GenerateCode());
        code.UpdateCode();
    }//GEN-LAST:event_CodeBtnMouseClicked

    private void lblskillsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblskillsMouseClicked
        // TODO add your handling code here:
        AddSkills skill= new AddSkills();
        skill.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblskillsMouseClicked

    private void lblskillsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblskillsMouseEntered
          lblskills.setBackground(new Color(51,110,123));  // TODO add your handling code here:
    }//GEN-LAST:event_lblskillsMouseEntered

    private void lblskillsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblskillsMouseExited
             lblskills.setBackground(new Color(0,153,153));  // TODO add your handling code here:
 // TODO add your handling code here:
    }//GEN-LAST:event_lblskillsMouseExited

    private void copybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copybtnActionPerformed
        StringSelection stringSelection = new StringSelection (CodeDisp.getText());
Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard ();
clpbrd.setContents (stringSelection, null);
    }//GEN-LAST:event_copybtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashDesign().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CodeBtn;
    private javax.swing.JTextField CodeDisp;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JButton copybtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblAppName;
    private javax.swing.JLabel lblD1;
    private javax.swing.JLabel lblDashboardTit;
    private javax.swing.JLabel lblDocument;
    private javax.swing.JLabel lblDocuments;
    private javax.swing.JLabel lblEmployerInt;
    private javax.swing.JLabel lblInt1;
    private javax.swing.JLabel lblInt2;
    private javax.swing.JLabel lblInt3;
    private javax.swing.JLabel lblNoDocuments;
    private javax.swing.JLabel lblNoPeople;
    private javax.swing.JLabel lblNoVideos;
    private javax.swing.JLabel lblOverview;
    private javax.swing.JLabel lblP1;
    private javax.swing.JLabel lblPeopleV;
    private javax.swing.JLabel lblSkills;
    private javax.swing.JLabel lblV1;
    private javax.swing.JLabel lblVideo;
    private javax.swing.JLabel lblVideos;
    private javax.swing.JLabel lblskills;
    // End of variables declaration//GEN-END:variables

    private void showpanel(JPanel PanelMenu) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
